spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: invoice-service
          uri: lb://invoice-service
          predicates:
            - Path=/invoices/**
        - id: scheduling-service
          uri: lb://scheduling-service
          predicates:
            - Path=/api/v1/**
      default-filters:
        - TokenRelay
        - LogFilter
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/GoLangInSpringCloud
        registration:
          keycloak-registration:
            provider: keycloak
            client-id: api-gateway
            client-secret: b86yVehVg5x2XtxqMpIme3GoRepojgzQ
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            scope:
              - openid
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG
    org.springframework.web: DEBUG